baseurl:
title: Tufte-Jekyll
subtitle: Content-centric blogging
author: Andrei Kashin
simple_search: http://google.com/search
description: A Jekyll theme for content-rich sites
name: tufte
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:short_year/:title/index.html
timezone: Europe/London
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: nvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Repos/akashin.me/
plugins: [jekyll-mermaid]
mermaid:
  src: '/js/mermaid.min.js'
